---

  # Need to add this machine to our virtual inventory first
- name: Setup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Add IP to Inventory
      ansible.builtin.add_host:
        name: "{{ip}}"


# Run the setup module to download all the host info
- name: Interview New Host
  hosts: "{{ip}}"
  user: "{{default_user}}"
  vars_files:
    - vault.yml  # Has the default_user/default_pass vars
  gather_facts: false
  tasks:
  - set_fact:
      ansible_password: "{{default_pass}}"
      device_role: "{{ role | default('server') }}"
  - name: Gatering Facts
    setup:


# Netbox fun goes here.

- name: Adding Information to Netbox
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vault.yml  # Has the default_user/default_pass vars
    - vars.yml

  tasks:
    - set_fact:
        ansible_password: "{{default_pass}}"
        device_role: "{{ role | default('server') }}"
    - name: Adding System Manufacturer
      netbox.netbox.netbox_manufacturer:
        netbox_url: "{{netbox_url}}"
        netbox_token: "{{netbox_token}}"
        state: present
        validate_certs: False
        data:
          name: "{{hostvars[ip].ansible_system_vendor}}"
    - name: Adding System Model
      netbox.netbox.netbox_device_type:
        netbox_url: "{{netbox_url}}"
        netbox_token: "{{netbox_token}}"
        validate_certs: False
        state: present
        data:
          model: "{{hostvars[ip].ansible_system_vendor}}"
          manufacturer: "{{hostvars[ip].ansible_system_vendor}}"

    - name: Adding Sytem to Devices
      netbox.netbox.netbox_device:
        netbox_url: "{{netbox_url}}"
        netbox_token: "{{netbox_token}}"
        validate_certs: False
        state: present
        data:
          name: "{{hostvars[ip].ansible_hostname}}"
          device_type: "{{hostvars[ip].ansible_system_vendor}}"
          device_role: "{{device_role}}"
          site: "{{default_site}}"

